language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.4.1
install:
  - pip install -U pip setuptools zope.testrunner
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"
script:
  - coverage run -m zope.testrunner --test-path=src --auto-color
after_success:
  - coveralls
notifications:
  email: false
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
